manifest:
  remotes:
    - name: olgam4
      url-base: https://github.com/olgam4
  projects:
    - name: zmk
      remote: olgam4
      revision: main
      import: app/west.yml
  self:
    path: config
